In [13]:
import pandas as pd 
import numpy as np
df=pd.read_csv('daily_us.csv')

print(df)

         date  states  positive  negative  pending  hospitalizedCurrently  \
0    20200724      56   4092928  45745166   3409.0                59670.0   
1    20200723      56   4017735  44890521   3179.0                59885.0   
2    20200722      56   3946708  44137149   3051.0                59675.0   
3    20200721      56   3877558  43410797   3197.0                59362.0   
4    20200720      56   3813916  42724191   3003.0                58371.0   
5    20200719      56   3756945  42070147   3052.0                57885.0   
6    20200718      56   3692061  41336523   3032.0                57645.0   
7    20200717      56   3626881  40640071   3002.0                57761.0   
8    20200716      56   3549648  39879912   2929.0                57442.0   
9    20200715      56   3478695  39123301   2947.0                56144.0   
10   20200714      56   3413313  38426686    960.0                55565.0   
11   20200713      56   3350434  37719583   2610.0                53988.0   

In [2]:
import numpy as np
x=np.arange(0,185).reshape(-1,1)
x

array([[  0],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [ 30],
       [ 31],
       [ 32],
       [ 33],
       [ 34],
       [ 35],
       [ 36],
       [ 37],
       [ 38],
       [ 39],
       [ 40],
       [ 41],
       [ 42],
       [ 43],
       [ 44],
       [ 45],
       [ 46],
       [ 47],
       [ 48],
       [ 49],
       [ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 57],
       [ 58],
       [ 59],
       [ 60],
       [ 61],
       [ 62],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 67],
       [ 68],
       [ 69],
       [ 70],
      

In [26]:
y=df['negative'].values
print(y)

[       0        0        0        0        0        0        0        0
        0        0        0        0        0        0        0        0
        0        0        0        0        0        0        0        0
        0        0        0        0        0        0        0        0
        0        0        0        0        0        0       14       17
      126      269     1180     1644     2289     2867     3474     4880
     6929    10220    14848    22994    26689    33042    49397    63104
    84997   108407   138814   177262   213476   260182   318687   390208
   474367   557979   645125   713082   809646   897282   980030  1070889
  1171834  1367775  1461880  1584951  1708456  1825410  1962049  2086091
  2192517  2303590  2412640  2538781  2645465  2778340  2905060  3022931
  3149393  3269209  3395710  3690277  3851303  4052986  4293235  4472143
  4644938  4826333  5038297  5241537  5503707  5721606  5932353  6141286
  6390308  6610085  6884239  7154484  7421283  7666

In [27]:
y=y.reshape(-1,1)
print(y)

[[       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [       0]
 [      14]
 [      17]
 [     126]
 [     269]
 [    1180]
 [    1644]
 [    2289]
 [    2867]
 [    3474]
 [    4880]
 [    6929]
 [   10220]
 [   14848]
 [   22994]
 [   26689]
 [   33042]
 [   49397]
 [   63104]
 [   84997]
 [  108407]
 [  138814]
 [  177262]
 [  213476]
 [  260182]
 [  318687]
 [  390208]
 [  474367]
 [  557979]
 [  645125]
 [  713082]
 [  809646]
 [  897282]
 [  980030]
 [ 1070889]
 [ 1171834]
 [ 1367775]
 [ 1461880]
 [ 1584951]
 [ 1708456]
 [ 1825410]
 [ 1962049]
 [ 2086091]
 [ 2192517]
 [ 2303590]
 [ 2412640]
 [ 2

In [28]:
import matplotlib.pyplot as plt 
plt.scatter(x,y)
plt.xlabel('days')
plt.ylabel('no of cases')
plt.show()

<Figure size 640x480 with 1 Axes>

In [29]:
from sklearn.linear_model import LinearRegression


In [30]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
reg=LinearRegression()

In [31]:
reg.fit(x_train,y_train)
y_pred=reg.predict(x_test)
print(y_pred)
reg.score(x_test,y_test)

[[-5777938.71083464]
 [ -560384.98271548]
 [25300533.4957882 ]
 [15092276.20164201]
 [23485732.19905109]
 [-6685339.35920319]
 [-4643687.90037395]
 [ 5337719.2316801 ]
 [16453377.17419484]
 [12143224.09444422]
 [11916373.93235208]
 [26888484.63043316]
 [ 5564569.39377223]
 [29610686.57553881]
 [  120165.50356093]
 [-6458489.19711105]
 [ 1481266.47611376]
 [-2148336.11736044]
 [ 8513621.50097002]
 [ 2615517.28657445]
 [27342184.95461744]
 [18041328.3088398 ]
 [23032031.87486682]
 [-3282586.92782113]
 [-8046440.33175602]
 [18495028.63302407]
 [ 3522917.934943  ]
 [-6004788.87292678]
 [28476435.76507812]
 [15545976.52582628]
 [ 6925670.36632506]
 [ 2388667.12448231]
 [16907077.49837911]
 [20536680.09185331]
 [ 4884018.90749582]
 [-3509437.08991327]
 [29837536.73763094]
 [ 4657168.74540368]
 [ 5110869.06958796]
 [-3055736.76572899]
 [-7365889.8454796 ]
 [ -787235.14480762]
 [20763530.25394545]
 [10328422.79770712]
 [23258882.03695896]
 [13504325.06699705]
 [14638575.87745773]
 [-1467785.63

0.8078547777621645

In [32]:
x_test=np.arange(185,208).reshape(-1,1)
x_test

array([[185],
       [186],
       [187],
       [188],
       [189],
       [190],
       [191],
       [192],
       [193],
       [194],
       [195],
       [196],
       [197],
       [198],
       [199],
       [200],
       [201],
       [202],
       [203],
       [204],
       [205],
       [206],
       [207]])

In [33]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [34]:
y_test=reg.predict(x_test)
print(y_test)

[[31418203.53108109]
 [31641421.50645162]
 [31864639.48182215]
 [32087857.45719268]
 [32311075.43256322]
 [32534293.40793374]
 [32757511.38330428]
 [32980729.35867481]
 [33203947.33404534]
 [33427165.30941588]
 [33650383.2847864 ]
 [33873601.26015694]
 [34096819.23552747]
 [34320037.210898  ]
 [34543255.18626853]
 [34766473.16163906]
 [34989691.1370096 ]
 [35212909.11238013]
 [35436127.08775066]
 [35659345.06312119]
 [35882563.03849173]
 [36105781.01386225]
 [36328998.98923279]]
